forge "http://forge.puppetlabs.com"

#mod "adamstrawson/byobu",
#       :git => "https://github.com/adamstrawson/puppet-byobu"

mod "hercules-team/augeasproviders",
       :git => "https://github.com/hercules-team/augeasproviders"
       
mod "torrancew/account",
       :git => "https://github.com/torrancew/puppet-account",
       :ref => 'v0.0.5'

mod "justinclayton/sudo",
       :git => "https://github.com/justinclayton/puppet-module-sudo",
       :ref => "1.0.0"

mod "puppetlabs/vcsrepo",
       :git => "https://github.com/puppetlabs/puppetlabs-vcsrepo"

mod "tohuwabohu/patch",
       :git => "https://github.com/tohuwabohu/tohuwabohu-patch.git"

mod "RobertBerger/yocto_users",
       :git => "https://github.com/RobertBerger/puppet-yocto-users"

mod "RobertBerger/docker_fixes",
       :git => "https://github.com/RobertBerger/puppet-docker-fixes"

mod "RobertBerger/ssh",
       :git => "https://github.com/RobertBerger/puppet-ssh"

mod "RobertBerger/autobuilder_before_install",
       :git => "https://github.com/RobertBerger/puppet-autobuilder-before-install"

mod "RobertBerger/autobuilder_after_install",
       :git => "https://github.com/RobertBerger/puppet-autobuilder-after-install"

